# Generated by Django 4.1.1 on 2022-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
